### ISSUE TITLE
a ? b : c ? d : e is deprecated php7.4 

### ISSUE THREAD

**Issue by MrDarkSkil** [pkly/i18next-php#4]
With php7.4 i got this error.

```
ErrorException: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in file /var/www/src/vendor/pkly/i18next-php/src/I18Next/PluralResolver.php on line 161
```

I can’t create a PR now, but when i have the time if is not done i will create one.

**Comment by pkly** [comment]
I'm kinda busy recently and have issues with health, if you create a pr I'll merge it and update the release
